# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix-p1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flix-p1
	pod "AlamofireImage"

  target 'Flix-p1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flix-p1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
